services:
  - type: web
    name: homecook-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://homecook-backend.onrender.com 